keys:
  - &router age19w5s8jcfzyxdt262vthc49unslhes86wfyz783qv84wnjaslfa4sdsfxes
  - &home-router age1hur9z8gfsj46n5tzdwlj4tgurjsdhh6pj6vtm2uf24q4gsf04agq3mmkh4
  - &yubikey ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAAGXGRGgDfeluY1/CjIz0Q745fexf8d/tDLCZ9SwHwZ 
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *router
        - *home-router
        - *yubikey
